import logging
from datetime import datetime
from typing import List

from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.notification import Notification
from app.models.user import User
from app.models.activity_log import ActivityLog
from app.core.config import settings

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Helper stubs – replace with real integrations later
# ---------------------------------------------------------------------------

def send_email(recipient: str, subject: str, html_body: str) -> bool:
    """Placeholder email sender.

    In production this should be wired to an SMTP server or a transactional
    email service (e.g. SendGrid, Amazon SES).  Returns ``True`` when the email
    is considered sent successfully.
    """
    logger.info("[Email Dispatcher] To: %s | Subject: %s", recipient, subject)
    # TODO: integrate real email client
    return True


def send_whatsapp(phone_number: str, message: str) -> bool:
    """Placeholder WhatsApp sender.

    In production this should call Twilio's API (or another provider).  Returns
    ``True`` when the message is considered delivered.
    """
    logger.info("[WhatsApp Dispatcher] To: %s | Message: %s", phone_number, message)
    # TODO: integrate real WhatsApp client
    return True

# ---------------------------------------------------------------------------
# Core dispatcher logic
# ---------------------------------------------------------------------------

async def _render_email_body(notification: Notification) -> str:
    """Render a simple HTML body for the notification.

    A more elaborate Jinja2 template can replace this stub later.
    """
    # Very basic HTML – the final version should live in a template file.
    return f"""
    <html>
      <body>
        <h2>{notification.title}</h2>
        <p>{notification.message or ''}</p>
        <footer>Generated by CAFlow on {datetime.utcnow().isoformat()} UTC</footer>
      </body>
    </html>
    """

async def dispatch_pending_notifications(db: AsyncSession) -> List[int]:
    """Fetch pending notifications, send them, and record audit logs.

    * **Pending** – ``sent_at`` is ``NULL`` and ``scheduled_at`` is either
      ``NULL`` or a datetime in the past.
    * For each notification we resolve the ``User`` to obtain e‑mail and phone
      details, invoke the stubbed ``send_email``/``send_whatsapp`` helpers based
      on user preferences (if the ``User`` model defines them – otherwise both
      channels are attempted), mark the notification as sent and write an
      ``ActivityLog`` entry of type ``NotificationSent``.
    * The function returns a list of ``Notification.id`` values that were
      processed – useful for tests or monitoring.
    """
    now = datetime.utcnow()

    # ---------------------------------------------------------------------
    # 1️⃣ Select pending notifications
    # ---------------------------------------------------------------------
    stmt = select(Notification).where(
        Notification.sent_at.is_(None),
        (Notification.scheduled_at.is_(None)) | (Notification.scheduled_at <= now)
    )
    result = await db.execute(stmt)
    pending: List[Notification] = result.scalars().all()

    processed_ids: List[int] = []

    for notif in pending:
        # Resolve the user – a simple join would be more efficient but this
        # keeps the logic clear for the stub implementation.
        user_stmt = select(User).where(User.id == notif.user_id)
        user_res = await db.execute(user_stmt)
        user: User = user_res.scalar_one_or_none()
        if not user:
            logger.warning("Notification %s has no associated user", notif.id)
            continue

        # -----------------------------------------------------------------
        # 2️⃣ Build message payloads
        # -----------------------------------------------------------------
        subject = notif.title
        html_body = await _render_email_body(notif)

        # -----------------------------------------------------------------
        # 3️⃣ Dispatch via configured channels (both for now)
        # -----------------------------------------------------------------
        email_sent = send_email(user.email, subject, html_body) if getattr(user, "email", None) else False
        whatsapp_sent = (
            send_whatsapp(user.phone_number, notif.message or notif.title)
            if getattr(user, "phone_number", None)
            else False
        )

        if not (email_sent or whatsapp_sent):
            logger.warning("Notification %s could not be sent – no contact info", notif.id)
            continue

        # -----------------------------------------------------------------
        # 4️⃣ Update ``sent_at`` timestamp
        # -----------------------------------------------------------------
        await db.execute(
            update(Notification)
            .where(Notification.id == notif.id)
            .values(sent_at=now)
        )

        # -----------------------------------------------------------------
        # 5️⃣ Create audit log entry
        # -----------------------------------------------------------------
        audit = ActivityLog(
            firm_id=notif.firm_id,
            actor_id=notif.user_id,
            action="NotificationSent",
            entity_type=notif.entity_type or "notification",
            entity_id=notif.id,
            entity_name=notif.title,
            details={
                "channels": {
                    "email": email_sent,
                    "whatsapp": whatsapp_sent,
                },
                "scheduled_at": notif.scheduled_at.isoformat() if notif.scheduled_at else None,
                "sent_at": now.isoformat(),
            },
        )
        db.add(audit)

        processed_ids.append(str(notif.id))

    # Commit all changes – the caller can also manage the transaction.
    await db.commit()
    logger.info("Dispatched %d notifications", len(processed_ids))
    return processed_ids
