"""Consolidated architectural updates

Revision ID: e1f733c3dd45
Revises: 001
Create Date: 2026-04-17 17:44:38.896068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f733c3dd45'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communication_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.Enum('email', 'whatsapp', 'sms', name='communicationchannel'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_templates_firm_id'), 'communication_templates', ['firm_id'], unique=False)
    op.create_table('notification_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.Enum('email', 'whatsapp', 'sms', name='notificationchannel'), nullable=False),
    sa.Column('trigger_event', sa.Enum('task_created', 'task_due_soon', 'task_overdue', 'compliance_due_soon', 'document_signature_requested', name='triggerevent'), nullable=False),
    sa.Column('days_offset', sa.Integer(), nullable=False),
    sa.Column('message_template', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_rules_firm_id'), 'notification_rules', ['firm_id'], unique=False)
    op.create_table('communication_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.Enum('email', 'whatsapp', 'sms', name='communicationchannel'), nullable=False),
    sa.Column('sent_to', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['communication_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_logs_client_id'), 'communication_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_communication_logs_firm_id'), 'communication_logs', ['firm_id'], unique=False)
    op.create_table('dsc_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('holder_name', sa.String(length=255), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('physical_location', sa.String(length=255), nullable=True),
    sa.Column('encrypted_pin', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsc_tokens_client_id'), 'dsc_tokens', ['client_id'], unique=False)
    op.create_index(op.f('ix_dsc_tokens_firm_id'), 'dsc_tokens', ['firm_id'], unique=False)
    op.create_table('encrypted_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('portal_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('encrypted_password', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encrypted_credentials_client_id'), 'encrypted_credentials', ['client_id'], unique=False)
    op.create_index(op.f('ix_encrypted_credentials_firm_id'), 'encrypted_credentials', ['firm_id'], unique=False)
    op.create_table('licenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('license_type', sa.String(length=100), nullable=False),
    sa.Column('license_number', sa.String(length=255), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('remind_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licenses_client_id'), 'licenses', ['client_id'], unique=False)
    op.create_index(op.f('ix_licenses_firm_id'), 'licenses', ['firm_id'], unique=False)
    op.create_table('attendance_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_in_lat', sa.Float(), nullable=True),
    sa.Column('check_in_lng', sa.Float(), nullable=True),
    sa.Column('check_out_lat', sa.Float(), nullable=True),
    sa.Column('check_out_lng', sa.Float(), nullable=True),
    sa.Column('work_location_type', sa.String(length=50), nullable=True),
    sa.Column('is_present', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_logs_date'), 'attendance_logs', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_logs_firm_id'), 'attendance_logs', ['firm_id'], unique=False)
    op.create_index(op.f('ix_attendance_logs_user_id'), 'attendance_logs', ['user_id'], unique=False)
    op.create_table('document_movements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('movement_type', sa.Enum('receipt', 'delivery', 'internal', name='movementtype'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('person_name', sa.String(length=255), nullable=True),
    sa.Column('staff_id', sa.UUID(), nullable=True),
    sa.Column('physical_location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_movements_client_id'), 'document_movements', ['client_id'], unique=False)
    op.create_index(op.f('ix_document_movements_firm_id'), 'document_movements', ['firm_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('leave_type', sa.Enum('casual', 'sick', 'annual', 'compensatory', 'wfh', 'half_day', name='leavetype'), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='leavestatus'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_firm_id'), 'leave_requests', ['firm_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_user_id'), 'leave_requests', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('timesheet_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firm_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['firm_id'], ['firms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timesheet_logs_client_id'), 'timesheet_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_timesheet_logs_firm_id'), 'timesheet_logs', ['firm_id'], unique=False)
    op.create_index(op.f('ix_timesheet_logs_task_id'), 'timesheet_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_timesheet_logs_user_id'), 'timesheet_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timesheet_logs_user_id'), table_name='timesheet_logs')
    op.drop_index(op.f('ix_timesheet_logs_task_id'), table_name='timesheet_logs')
    op.drop_index(op.f('ix_timesheet_logs_firm_id'), table_name='timesheet_logs')
    op.drop_index(op.f('ix_timesheet_logs_client_id'), table_name='timesheet_logs')
    op.drop_table('timesheet_logs')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_leave_requests_user_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_firm_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_document_movements_firm_id'), table_name='document_movements')
    op.drop_index(op.f('ix_document_movements_client_id'), table_name='document_movements')
    op.drop_table('document_movements')
    op.drop_index(op.f('ix_attendance_logs_user_id'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_firm_id'), table_name='attendance_logs')
    op.drop_index(op.f('ix_attendance_logs_date'), table_name='attendance_logs')
    op.drop_table('attendance_logs')
    op.drop_index(op.f('ix_licenses_firm_id'), table_name='licenses')
    op.drop_index(op.f('ix_licenses_client_id'), table_name='licenses')
    op.drop_table('licenses')
    op.drop_index(op.f('ix_encrypted_credentials_firm_id'), table_name='encrypted_credentials')
    op.drop_index(op.f('ix_encrypted_credentials_client_id'), table_name='encrypted_credentials')
    op.drop_table('encrypted_credentials')
    op.drop_index(op.f('ix_dsc_tokens_firm_id'), table_name='dsc_tokens')
    op.drop_index(op.f('ix_dsc_tokens_client_id'), table_name='dsc_tokens')
    op.drop_table('dsc_tokens')
    op.drop_index(op.f('ix_communication_logs_firm_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_client_id'), table_name='communication_logs')
    op.drop_table('communication_logs')
    op.drop_index(op.f('ix_notification_rules_firm_id'), table_name='notification_rules')
    op.drop_table('notification_rules')
    op.drop_index(op.f('ix_communication_templates_firm_id'), table_name='communication_templates')
    op.drop_table('communication_templates')
    # ### end Alembic commands ###
